name: cloudbeaver

services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace/
    networks:
      - postgres
      - nginx

volumes:
  cloudbeaver_data:

networks:
  nginx:
    external: true
  postgres:
    external: true
