name: postgres

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-16
    environment:
      POSTGRES_USER: luucx7
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    volumes:
      - postgres_16_data:/var/lib/postgresql/data
    networks:
      - postgres
    restart: unless-stopped

volumes:
  postgres_16_data:
    name: 'postgres_16_data'

networks:
  postgres:
    name: postgres
    external: true

